AWSTemplateFormatVersion: 2010-09-09
Description: |
  dumenden cfn show
Parameters:
  myKeypair:
    Description: choose your keypair
    Type: AWS::EC2::KeyPair::KeyName
    Default: firstkey

  myInstanceType:
    Description: choose your instance
    Type: String
    Default: t2.micro
    AllowedValues:
         - t2.micro
         - t3.micro
         - t3.small

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'

  
Resources:

  myWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref myInstanceType
      KeyName: !Ref myKeypair
      SecurityGroupIds: 
        - !Ref mySecGrp
      Tags: 
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack 
          #substutional henüz üretilmedi demek
      UserData: !Base64 |
        #! /bin/bash
        dnf update -y
        dnf install httpd -y
        systemctl start httpd
        systemctl enable httpd
        cd /var/www/html
        FOLDER="https://raw.githubusercontent.com/muhsinnnn/staticWebsiteCfn/refs/heads/main/static-web"
        wget ${FOLDER}/index.html
        wget ${FOLDER}/cat0.jpg
        wget ${FOLDER}/cat1.jpg
        wget ${FOLDER}/cat2.jpg


  mySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow ssh and http # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: muh-cohort18-kitten


Outputs:
  webSiteURL:
    Description: ip of website 
    Value: !Sub 
      - http://${publicIP}
      - publicIP: !GetAtt myWebServer.PublicIp